---

# Default user to create buildbots under, set this on a per host level
# to match existing buildslave users if applicable.
buildslave_user: void-buildslave

# Additional groups for the buildslave user.  At minimum this must
# contain xbuilder for the chroot to work correctly within xbps-src
buildslave_groups:
  - xbuilder

# Is this a remote builder?  The general case is yes since builders
# are heavy computationally and only a limited number can run on the
# buildmaster.  This sets up the sync job to exfiltrate the build
# artifacts back to the master repo.
buildslave_isremote: true

# Default user to syncronize with main repo.  This user gets read
# access on the /hostdir but that's it.
buildslave_sync_user: void-buildsync

# Default location to provision new buildslaves into.  Set this on a
# per host level to match existing buildslave home folders if
# applicable.
buildslave_rootdir: /home/void-buildslave/

# At which server does the buildmaster reside?  This should be in the
# form of a dotted hostname or an IP address.  While this may be
# overriden in the case of builders running on the buildmaster itself
# to 'localhost', it is preferred to use the full canonical name in
# all locations for consistency.  If persistent resolution issues are
# preventing a host from connecting to the buildmaster this name
# should very likely be specified in the hosts file.
buildslave_master: localhost

# The following list contains hashes for the builders.  For standards
# and sake of debugging, the 'mach' should be the architecture as
# specified by `xbps-uhelper arch`.  Only the name is required, though
# if existing builders are being captured for ansible management, the
# directory and service_name should be specified to match those of the
# existing buildbot directory name and runit service directory
# respecitvely.

# buildslave_buildslaves:
#   - name: x86_64-primary
#     mach: x86_64
#     directory: x86_64
#     service_name: arbitrary-builder-name
#     zone: Zone-for-this-builder

# The following hash is shown for structure, but should never be
# present in a commited file.  This hash contains the secure usernames
# and passwords which are recognized by the buildmaster.  At least one
# complete copy of this must be available to at least a single
# infrastructure maintainer in order to deploy the buildmaster.  To
# re-iterate: never commit this hash under any circumstances, it is to
# be included from the secret/ directory and by default will be
# included from the 'secret/buildslave_credentials.yml' path.  In
# order for this map to work correctly, the architecture must match
# exactly that of the builder that is performing the lookup as
# specified in the above list.  For standards, use architecture
# identifiers as they would be printed by `xbps-uhelper arch`.

# buildslave_credentials:
#   username: password
# Where the username and password fields are as follows:
#     username: name of the builder
#     password: password to connect to the buildmaster with

