---
- hosts: buildmaster
  become: yes
  become_user: root
  become_method: su
  roles:
    - buildmaster
    - root-mirror-shim
    - void-updates

- hosts: buildslave
  become: yes
  become_user: root
  become_method: su
  roles:
    - buildslave
    - btimefiles
