---
- name: Configure webserver
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: buildmaster
        static_root: false
        urls:
          - build.voidlinux.org
        tls:
          certificate: "{{ buildmaster_ssl_cert_path | default('/dev/null') }}"
          key: "{{ buildmaster_ssl_certkey_path | default('/dev/null') }}"
          stapling: yes

- name: Install root location block
  copy:
    src: buildmaster_root.conf
    dest: /etc/nginx/locations.d/build.voidlinux.org/
    owner: root
    group: root
    mode: 0644
